version: '3.3'

services:
    backend:
        build: backend
        env_file: 
        - backend/.env
        ports:
            - "5050:5050"

    vue-app:
        build: frontend
        env_file: frontend/.env.production
        ports:
            - "8080:8080"